server:
  port: 8080

spring:
  #数据库连接信息
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emall
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tKrz2u2GdbY768nppH5
    accessKeySecret: sVsHQlDDgmrVhD9TEXMP5Ty4m275gC
    bucketName: tlias-zincoid